apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: urs7wfg1q-dotnet-basic
  janus-idp.io/tekton: urs7wfg1q-dotnet-basic
  backstage.io/kubernetes-id: urs7wfg1q-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: urs7wfg1q-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
